global using Xunit;
global using FluentAssertions;
global using Moq;
global using Logs2Obs.Core.Models;
global using Logs2Obs.Core.Abstractions;
global using Logs2Obs.Core.Query;
global using Logs2Obs.Core.Commands;
global using Logs2Obs.Core.Exceptions;
global using Microsoft.Extensions.Logging.Abstractions;
