global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'logs2obs-api'
    static_configs:
      - targets: ['logs2obs-api:8080']
    metrics_path: '/metrics'

  - job_name: 'logs2obs-queryengine'
    static_configs:
      - targets: ['logs2obs-queryengine:8081']
    metrics_path: '/metrics'
