global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'logs2obs-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'

  - job_name: 'logs2obs-worker'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'

  - job_name: 'logs2obs-queryengine'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/metrics'
