namespace Logs2Obs.Adapters.Local.AI;

using System.Net.Http.Json;
using System.Text.Json.Serialization;
using Logs2Obs.Core.Abstractions;
using Logs2Obs.Core.Exceptions;
using Logs2Obs.Core.Graphs;
using Logs2Obs.Core.Models;
using Logs2Obs.Core.Resilience;
using Logs2Obs.Adapters.Local.Options;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

public sealed class OllamaAiService(
    IHttpClientFactory httpClientFactory,
    IOptions<OllamaOptions> options,
    ILogger<OllamaAiService> logger) : IAiService
{
    private readonly OllamaOptions _opts = options.Value;

    public async Task<AiSqlResult> GenerateSqlAsync(string tenantId, string naturalLanguage, string schemaContext, CancellationToken ct = default)
    {
        var pipeline = ResiliencePipelines.ForExternalIo<AiSqlResult>();
        return await pipeline.ExecuteAsync(async token =>
        {
            try
            {
                var http = httpClientFactory.CreateClient("ollama");
                http.Timeout = TimeSpan.FromSeconds(_opts.TimeoutSeconds);

                var prompt = $"""
                    Convert this to SQL for the logs2obs schema: {naturalLanguage}
                    Schema: {schemaContext}
                    Return only valid SQL.
                    """;

                var request = new OllamaGenerateRequest
                {
                    Model = _opts.ModelName,
                    Prompt = prompt,
                    Stream = false,
                    Options = new OllamaModelOptions { NumPredict = _opts.MaxTokens }
                };

                using var response = await http.PostAsJsonAsync($"{_opts.BaseUrl}/api/generate", request, token);
                response.EnsureSuccessStatusCode();

                var body = await response.Content.ReadFromJsonAsync<OllamaGenerateResponse>(token);
                if (body is null || string.IsNullOrWhiteSpace(body.Response))
                    throw new AiQueryException("Ollama returned empty response.");

                var sql = body.Response.Trim();
                var schema = new QueryResultSchema();
                var suggestions = GraphSuggestionEngine.SuggestFromSchema(schema);
                var graphType = suggestions.Count > 0 ? suggestions[0].GraphType : GraphType.LineChart;

                logger.LogInformation("Ollama generated SQL for tenant {TenantId}: {Sql}", tenantId, sql);

                return new AiSqlResult
                {
                    Sql = sql,
                    Explanation = $"Generated by Ollama model {_opts.ModelName}",
                    SuggestedGraphType = graphType,
                    InputTokenCount = body.PromptEvalCount ?? 0,
                    OutputTokenCount = body.EvalCount ?? 0,
                    ModelUsed = _opts.ModelName
                };
            }
            catch (AiQueryException)
            {
                throw;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Ollama AI service failed for tenant {TenantId}", tenantId);
                throw new AiQueryException($"Ollama request failed: {ex.Message}");
            }
        }, ct);
    }
}

file sealed class OllamaGenerateRequest
{
    [JsonPropertyName("model")] public required string Model { get; init; }
    [JsonPropertyName("prompt")] public required string Prompt { get; init; }
    [JsonPropertyName("stream")] public bool Stream { get; init; } = false;
    [JsonPropertyName("options")] public OllamaModelOptions? Options { get; init; }
}

file sealed class OllamaModelOptions
{
    [JsonPropertyName("num_predict")] public int NumPredict { get; init; }
}

file sealed class OllamaGenerateResponse
{
    [JsonPropertyName("response")] public string? Response { get; init; }
    [JsonPropertyName("prompt_eval_count")] public int? PromptEvalCount { get; init; }
    [JsonPropertyName("eval_count")] public int? EvalCount { get; init; }
}
